parameters:
    tchoulom.viewcounter.command.base.class: Tchoulom\ViewCounterBundle\Command\AbstractCommand
    tchoulom.viewcounter.cleanup.command.class: Tchoulom\ViewCounterBundle\Command\ViewcounterCleanupCommand
    tchoulom.viewcounter.stats_converter.command.class: Tchoulom\ViewCounterBundle\Command\StatsConverterCommand

services:

    # Abstract Command
    tchoulom.viewcounter.command.base:
        class: '%tchoulom.viewcounter.command.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@tchoulom.viewcounter.manager'
            - '@tchoulom.viewcounter.stats_manager'

    # CleanupViewcounterCommand
    tchoulom.viewcounter.cleanup.command:
        class: '%tchoulom.viewcounter.cleanup.command.class%'
        parent: tchoulom.viewcounter.command.base
        public: true
        tags:
            - { name: console.command }

    # StatsConverterCommand
    tchoulom.viewcounter.stats_converter.command:
        class: '%tchoulom.viewcounter.stats_converter.command.class%'
        parent: tchoulom.viewcounter.command.base
        public: true
        arguments:
            - '@tchoulom.viewcounter.stats_converter'
        tags:
            - { name: console.command }

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Command\AbstractCommand: '@tchoulom.viewcounter.command.base'
    Tchoulom\ViewCounterBundle\Command\ViewcounterCleanupCommand: '@tchoulom.viewcounter.cleanup.command'
    Tchoulom\ViewCounterBundle\Command\StatsConverterCommand: '@tchoulom.viewcounter.stats_converter.command'
