parameters:
    tchoulom.viewcounter.stats_manager.class: Tchoulom\ViewCounterBundle\Manager\StatsManager
    tchoulom.viewcounter.file_stats_builder.class: Tchoulom\ViewCounterBundle\Builder\FileStatsBuilder
    tchoulom.viewcounter.file_stats_finder.class: Tchoulom\ViewCounterBundle\Finder\FileStatsFinder
    tchoulom.viewcounter.stats_computer.class: Tchoulom\ViewCounterBundle\Compute\StatsComputer
    tchoulom.viewcounter.stats_converter.class: Tchoulom\ViewCounterBundle\ETL\StatsConverter

services:
    # Statistics
    tchoulom.viewcounter.stats_manager:
        class: '%tchoulom.viewcounter.stats_manager.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter.storage_adapter'
            - '@tchoulom.viewcounter.file_stats_builder'

    # FileStatsBuilder
    tchoulom.viewcounter.file_stats_builder:
        class: '%tchoulom.viewcounter.file_stats_builder.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.geolocator_adapter']

    # FileStatsFinder
    tchoulom.viewcounter.file_stats_finder:
        class: '%tchoulom.viewcounter.file_stats_finder.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.filesystem_storage']

    # StatsComputer
    tchoulom.viewcounter.stats_computer:
        class: '%tchoulom.viewcounter.stats_computer.class%'
        public: true

    # StatsConverter
    tchoulom.viewcounter.stats_converter:
        class: '%tchoulom.viewcounter.stats_converter.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter.filesystem_storage'

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Manager\StatsManager: '@tchoulom.viewcounter.stats_manager'
    Tchoulom\ViewCounterBundle\Builder\FileStatsBuilder: '@tchoulom.viewcounter.file_stats_builder'
    Tchoulom\ViewCounterBundle\Finder\FileStatsFinder: '@tchoulom.viewcounter.file_stats_finder'
    Tchoulom\ViewCounterBundle\Compute\StatsComputer: '@tchoulom.viewcounter.stats_computer'
    Tchoulom\ViewCounterBundle\ETL\StatsConverter: '@tchoulom.viewcounter.stats_converter'
