parameters:
    tchoulom.viewcounter.storage_adapter.class: Tchoulom\ViewCounterBundle\Adapter\Storage\StorageAdapter
    tchoulom.viewcounter.filesystem_storage.class: Tchoulom\ViewCounterBundle\Storage\Filesystem\FilesystemStorage
    tchoulom.viewcounter.mongodb_storage.class: Tchoulom\ViewCounterBundle\Storage\Database\MongoDB\MongoDBStorage

services:
    # Storage Adapter
    tchoulom.viewcounter.storage_adapter:
        class: '%tchoulom.viewcounter.storage_adapter.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter.filesystem_storage'

    # FilesystemStorage
    tchoulom.viewcounter.filesystem_storage:
        class: '%tchoulom.viewcounter.filesystem_storage.class%'
        public: true
        arguments:
            - '%kernel.project_dir%'
            - '@tchoulom.viewcounter_config'
            - '@tchoulom.viewcounter.file_stats_builder'

    # MongoDBStorage
    tchoulom.viewcounter.mongodb_storage:
        class: '%tchoulom.viewcounter.mongodb_storage.class%'
        public: true
        arguments:
            - ~
            - '@tchoulom.viewcounter.geolocator_adapter'

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Adapter\FileStorageAdapter: '@tchoulom.viewcounter.storage_adapter'
    Tchoulom\ViewCounterBundle\Storage\Filesystem\FilesystemStorage: '@tchoulom.viewcounter.filesystem_storage'
    Tchoulom\ViewCounterBundle\Storage\Database\MongoDB\MongoDBStorage: '@tchoulom.viewcounter.mongodb_storage'
