parameters:
    tchoulom.viewcounter.base.class: Tchoulom\ViewCounterBundle\Counter\AbstractViewCounter
    tchoulom.viewcounter.class: Tchoulom\ViewCounterBundle\Counter\ViewCounter
    tchoulom.viewcounter.manager.class: Tchoulom\ViewCounterBundle\Manager\CounterManager
    tchoulom.viewcounter_config.class: Tchoulom\ViewCounterBundle\Model\ViewcounterConfig
    tchoulom.viewcounter_node_config.class: Tchoulom\ViewCounterBundle\Model\ViewcounterNodeConfig
    tchoulom.statistics_node_config.class: Tchoulom\ViewCounterBundle\Model\StatisticsNodeConfig

services:
    # Counter
    tchoulom.viewcounter.base:
        class: '%tchoulom.viewcounter.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@tchoulom.viewcounter.manager'
            - '@request_stack'
            - '@tchoulom.viewcounter_config'
        calls:
            - [setStatsManager, ['@tchoulom.viewcounter.stats_manager']]

    tchoulom.viewcounter:
        class: '%tchoulom.viewcounter.class%'
        public: true
        parent: tchoulom.viewcounter.base

    # Manager
    tchoulom.viewcounter.manager:
        class: '%tchoulom.viewcounter.manager.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter.repository'

    # Viewcounter configuration
    tchoulom.viewcounter_config:
        class: '%tchoulom.viewcounter_config.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter_node_config'
            - '@tchoulom.statistics_node_config'

    # Viewcounter node configuration
    tchoulom.viewcounter_node_config:
        class: '%tchoulom.viewcounter_node_config.class%'
        public: true
        arguments: [~]

    # Statistics node configuration
    tchoulom.statistics_node_config:
        class: '%tchoulom.statistics_node_config.class%'
        public: true
        arguments: [~]

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Counter\AbstractViewCounter: '@tchoulom.viewcounter.base'
    Tchoulom\ViewCounterBundle\Counter\ViewCounter: '@tchoulom.viewcounter'
    Tchoulom\ViewCounterBundle\Manager\CounterManager: '@tchoulom.viewcounter.manager'
    Tchoulom\ViewCounterBundle\Model\ViewcounterConfig: '@tchoulom.viewcounter_config'
    Tchoulom\ViewCounterBundle\Model\ViewcounterNodeConfig: '@tchoulom.viewcounter_node_config'
    Tchoulom\ViewCounterBundle\Model\StatisticsNodeConfig: '@tchoulom.statistics_node_config'
